---
{{- if .Values.istio.virtualService.envoyFilter.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rate-limit
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  workloadSelector:
    labels:
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: {{ .Values.istio.virtualService.envoyFilter.maxRequests }}
                tokens_per_fill: {{ .Values.istio.virtualService.envoyFilter.maxRequests }}
                fill_interval: {{ .Values.istio.virtualService.envoyFilter.interval }}
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: true
                  header:
                    key: x-istio-rate-limit
                    value: 'true'
{{- end }}