---
{{- if .Values.istio.enabled -}}
{{- $fullName := include "freshrss.fullname" . -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $fullName }}
spec:
  host: {{ include "freshrss.fullname" . }}.{{ .Release.Namespace}}.svc.cluster.local
  {{- with .Values.istio.virtualService.trafficPolicy }}
  trafficPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  subsets:
  - name: main
    labels:
      app: {{ $fullName }}
      version: {{ .Values.podLabels.version }}
{{- end }}