{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freshrss.fullname" . }}-data
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freshrss.fullname" . }}-extensions
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
  - ReadWriteOnce
{{- end }}