{{- if .Values.istio.enabled -}}
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: prometheus-metrics
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - tagOverrides:
        request_method:
          value: "request.method"
        request_host:
          value: "request.host"
{{- end }}