# k8s-us-east-1 values

ingress:
  enabled: false
  className: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-dns01-aws
  hosts:
    - host: rss.unreliable.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - secretName: freshrss-tls
    hosts:
      - rss.unreliable.cloud

podAnnotations:
  backup.velero.io/backup-volumes: "freshrss-data,freshrss-extensions"

podLabels:
  app: freshrss

persistence:
  enabled: true
  storageClassName: hcloud-volumes

velero:
  enabled: true
  backupSchedule:
    schedule: '@every 24h'
    template:
      includeClusterResources: true
      includedNamespaces:
      - freshrss
      includedResources:
      - '*'
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: freshrss
      snapshotVolumes: true
      storageLocation: velero-hetzner-aws
      ttl: 360h0m0s
      volumeSnapshotLocations:
      - velero-hetzner-aws

istio:
  enabled: true
  gateway:
    hostName: rss.unreliable.cloud
    selector: ingressgateway
    tls:
      enabled: true
      credentialName: freshrss-tls
      issuer:
        name: letsencrypt-dns01-aws
        kind: ClusterIssuer
  virtualService:
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: connect-failure,refused-stream,gateway-error
    trafficPolicy:
      connectionPool:
        http:
          h2UpgradePolicy: UPGRADE
          maxRequestsPerConnection: 100
      outlierDetection:
        consecutive5xxErrors: 30
        interval: 5m
        baseEjectionTime: 5m